### ISSUE TITLE
Sprockets::Rails::Helper::AssetFilteredError in Pages#welcome

### ISSUE THREAD

**Issue by darksheer** [chukcha-wtf/adminlte-generators#1]
Gave the setup proceedures a go and generated a new controller:

rails generate controller Pages welcome

Getting the following error:

![image](https://cloud.githubusercontent.com/assets/1522288/8223788/3fe4b9c2-1531-11e5-9bad-655c4a0f50ac.png)

**Comment by chukcha-wtf** [comment]
Thanks for pointing out, it's fixed in https://github.com/chukcha-wtf/adminlte-generators/commit/7ead0f1db451efbd89686e68a61a0a3878aac024. You should be able to simply use `gem 'adminlte-generators' '~> 0.2.4'`

**Comment by darksheer** [comment]
Thanks for the help--now there is a new error:

undefined local variable or method `root_path' for #<#Class:0x007f8a52dd34a0:0x007f8a52dd2938>

**Comment by chukcha-wtf** [comment]
Yeah, that's because you don't have root_path configured in your routes. Current version of gem suppose that you have one, after all - everyone has a `root_path` :smile:
